### PR TITLE
Bump major version, warn about `bifunctor-classes-compat` migration in CHANGELOG

### PR DESCRIPTION
**Pull request by RyanGlScott**
Addresses #114.

### CODE REVIEW

**Review by phadej — APPROVED** [review]
:+1:

**Comment by phadej** [comment]
The problem happens e.g. in https://github.com/haskellari/these/actions/runs/4408803121/jobs/7724289572 (not sure how long the logs will stay on).

As `strict` depends on `bifunctors`, and tries to define `Assoc` which has `bifunctor-classes-compat.Bifunctor` as a superclass in newer `assoc`, things go wrong if I'd just relax bounds in `strict` (as I do in the job with `allow-newer`).

So there is a concrete example of why bumping major version when moving from `bifunctors` to `bifunctors-classes-compat` as a compat package is very much justified.

That's unfortunate cascade of major bumps, but at least they all hit at once.

---

I'll proceed with major releases of `these` and `semialign`, and probably `strict` as well.

**Comment by RyanGlScott** [comment]
Good to know. Indeed, this was a perfect storm of several things being migrated, and I don't know how to do better other than signalling users to look carefully via major version bumps. Thanks for taking care of these!

**Comment by phadej** [comment]
Another issue I found is that old `lens` may depend on newer `bifunctors`, and it defines type-classes like `Bifunctor f => Swapped f` with wrong `Bifunctor` as super-class.

`semigroupoids` defined `Biapply`, but it got major revision, so it works.

Maybe `bifunctors-5.6` should been `bifunctors-6`, but maybe it's only few `lens` versions which can be revised.

**Comment by RyanGlScott** [comment]
Ah, I see. Do you know what is the most recent `lens` version that is affected by this?

**Comment by phadej** [comment]
> Ah, I see. Do you know what is the most recent lens version that is affected by this?

`lens-5` started using `assoc` for `Swap` instead of `Swapped`.

**Comment by RyanGlScott** [comment]
OK, so `lens-5` and up, then? What in particular needs to be revised? The `assoc` upper version bounds? The `bifunctors` upper version bounds? Something else?

**Comment by phadej** [comment]
Wait. The revision won't help, as `lens` is consistent and failing build plan is using `bifunctors-5.5.15`.

I have to figure out my own code defining `Swapped` instances for types **I** define only `bifunctor-classes-compat.Bifunctor` instance.

**Pull request merged**
